name: my-first-wf

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Its me dinesh"
      - name: print end
        run: echo "Bye by Din"
      - name: parallel exec
        run: |
            echo "First output"
            echo "Second output"
